name             "postgres"
maintainer       "Phil Cohen"
maintainer_email "github@phlippers.net"
license          "MIT"
description      "Installs PostgreSQL, The world's most advanced open source database."
long_description IO.read(File.join(File.dirname(__FILE__), "README.md"))
version          "0.16.1"

recipe "postgres",                   "Set up the apt repository and install dependent packages"
recipe "postgres::apt_repository",   "Internal recipe to setup the apt repository"
recipe "postgres::client",           "Front-end programs for PostgreSQL 9.x"
recipe "postgres::configuration",    "Internal recipe to manage configuration files"
recipe "postgres::contrib",          "Additional facilities for PostgreSQL"
recipe "postgres::data_directory",   "Internal recipe to setup the data directory"
recipe "postgres::dbg",              "Debug symbols for the server daemon"
recipe "postgres::debian_backports", "Internal recipe to manage debian backports"
recipe "postgres::doc",              "Documentation for the PostgreSQL database management system"
recipe "postgres::libpq",            "PostgreSQL C client library and header files for libpq5 (PostgreSQL library)"
recipe "postgres::postgis",          "Geographic objects support for PostgreSQL 9.x"
recipe "postgres::server",           "Object-relational SQL database, version 9.x server"
recipe "postgres::server_dev",       "Development files for PostgreSQL server-side programming"
recipe "postgres::service",          "Internal recipe to declare the system service"
recipe "postgres::setup_databases",  "Internal recipe to manage specified databases"
recipe "postgres::setup_extensions", "Internal recipe to manage specified database extensions"
recipe "postgres::setup_languages",  "Internal recipe to manage specified database languages"
recipe "postgres::setup_users",      "Internal recipe to manage specified users"

supports "ubuntu"
supports "debian"

depends "apt", ">= 2.6.1"
suggests "minitest-handler"
